# Generated by Django 4.2.7 on 2025-09-30 19:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistanceCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título resumido do caso (visível publicamente após aprovação)",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "public_description",
                    models.TextField(
                        help_text="Descrição que será exibida no feed após aprovação",
                        verbose_name="Descrição Pública",
                    ),
                ),
                (
                    "internal_description",
                    models.TextField(
                        help_text="Informações confidenciais para Conselho Diretor e Fiscal apenas",
                        verbose_name="Descrição Interna",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor solicitado para o caso (R$)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("pending_approval", "Pendente de Aprovação"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aprovado em"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Explicação do Conselho Fiscal sobre a rejeição",
                        verbose_name="Motivo da Rejeição",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Membro do Conselho Diretor que criou o caso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Membro do Conselho Fiscal que aprovou/rejeitou",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso de Assistência",
                "verbose_name_plural": "Casos de Assistência",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="PDF, imagem ou documento (máx. 5MB)",
                        upload_to="assistance_attachments/%Y/%m/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Nome original do arquivo",
                        max_length=255,
                        verbose_name="Nome do Arquivo",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        help_text="Extensão do arquivo (PDF, JPG, PNG, etc.)",
                        max_length=50,
                        verbose_name="Tipo de Arquivo",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        help_text="Tamanho do arquivo em bytes", verbose_name="Tamanho"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="assistance.assistancecase",
                        verbose_name="Caso",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo",
                "verbose_name_plural": "Anexos",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="assistancecase",
            index=models.Index(
                fields=["-created_at"], name="assistance__created_3e7de4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assistancecase",
            index=models.Index(
                fields=["status", "-created_at"], name="assistance__status_6f978d_idx"
            ),
        ),
    ]
