# Generated by Django 4.2.7 on 2025-10-02 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_donationrequest_voluntarydonation_delete_donation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assistance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistancecase",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que o admin validou e finalizou o caso",
                null=True,
                verbose_name="Concluído em",
            ),
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="donation_request",
            field=models.OneToOneField(
                blank=True,
                help_text="Solicitação que originou este caso (se aplicável)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistance_case",
                to="finance.donationrequest",
                verbose_name="Solicitação de Doação",
            ),
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="proof_submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que o membro enviou os comprovantes",
                null=True,
                verbose_name="Comprovante Enviado em",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("payment_proof", "Comprovante de Pagamento"),
                    ("photo_evidence", "Foto da Doação"),
                    ("other", "Outro Documento"),
                ],
                default="other",
                help_text="Tipo de comprovante/documento",
                max_length=20,
                verbose_name="Tipo de Anexo",
            ),
        ),
        migrations.AlterField(
            model_name="assistancecase",
            name="created_by",
            field=models.ForeignKey(
                help_text="Membro que criou/solicitou o caso",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AlterField(
            model_name="assistancecase",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin que validou o caso/comprovantes",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisado por",
            ),
        ),
        migrations.AlterField(
            model_name="assistancecase",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("pending_approval", "Pendente de Aprovação"),
                    ("awaiting_proof", "Aguardando Comprovação"),
                    ("proof_submitted", "Comprovante Enviado"),
                    ("completed", "Concluído"),
                    ("rejected", "Rejeitado"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
