# Generated by Django 4.2.7 on 2025-10-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0002_assistancecase_completed_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assistancecase",
            name="proof_submitted_at",
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="member_proof_submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que o membro enviou comprovantes da aplicação ao beneficiário",
                null=True,
                verbose_name="Comprovante do Membro Enviado em",
            ),
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="transfer_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que admin confirmou a transferência ao membro",
                null=True,
                verbose_name="Transferência Confirmada em",
            ),
        ),
        migrations.AlterField(
            model_name="assistancecase",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("pending_approval", "Pendente de Aprovação"),
                    ("awaiting_transfer", "Aguardando Transferência do Admin"),
                    ("awaiting_member_proof", "Aguardando Comprovação do Membro"),
                    ("pending_validation", "Pendente de Validação Final"),
                    ("completed", "Concluído"),
                    ("rejected", "Rejeitado"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
