# Generated by Django 4.2.7 on 2025-10-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0003_remove_assistancecase_proof_submitted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistancecase",
            name="bank_info_submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que o membro informou os dados bancários do beneficiário",
                null=True,
                verbose_name="Dados Bancários Informados em",
            ),
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="beneficiary_account",
            field=models.CharField(
                blank=True,
                help_text="Número da conta com dígito (ex: 12345-6)",
                max_length=20,
                verbose_name="Conta",
            ),
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="beneficiary_account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("corrente", "Conta Corrente"),
                    ("poupanca", "Conta Poupança"),
                    ("pagamento", "Conta Pagamento"),
                ],
                max_length=20,
                verbose_name="Tipo de Conta",
            ),
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="beneficiary_agency",
            field=models.CharField(
                blank=True,
                help_text="Número da agência (sem dígito)",
                max_length=10,
                verbose_name="Agência",
            ),
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="beneficiary_bank",
            field=models.CharField(
                blank=True,
                help_text="Nome do banco (ex: Banco do Brasil, Caixa, Nubank)",
                max_length=100,
                verbose_name="Banco",
            ),
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="beneficiary_cpf",
            field=models.CharField(
                blank=True,
                help_text="CPF do beneficiário (formato: 000.000.000-00)",
                max_length=14,
                verbose_name="CPF do Beneficiário",
            ),
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="beneficiary_name",
            field=models.CharField(
                blank=True,
                help_text="Nome completo do beneficiário da doação",
                max_length=200,
                verbose_name="Nome do Beneficiário",
            ),
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="beneficiary_pix_key",
            field=models.CharField(
                blank=True,
                help_text="Chave PIX (CPF, e-mail, telefone ou chave aleatória)",
                max_length=200,
                verbose_name="Chave PIX",
            ),
        ),
        migrations.AlterField(
            model_name="assistancecase",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("pending_approval", "Pendente de Aprovação"),
                    ("awaiting_bank_info", "Aguardando Dados Bancários"),
                    ("awaiting_transfer", "Aguardando Transferência do Admin"),
                    ("awaiting_member_proof", "Aguardando Comprovação do Membro"),
                    ("pending_validation", "Pendente de Validação Final"),
                    ("completed", "Concluído"),
                    ("rejected", "Rejeitado"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
