# Generated by Django 5.2.5 on 2025-10-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0005_casetimeline"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="casetimeline",
            new_name="assistance__case_id_fef8eb_idx",
            old_name="assistance_case_id_created_idx",
        ),
        migrations.RenameIndex(
            model_name="casetimeline",
            new_name="assistance__event_t_2a646d_idx",
            old_name="assistance_event_type_created_idx",
        ),
    ]
