# Generated by Django 4.2.7 on 2025-10-03 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "assistance",
            "0006_rename_assistance_case_id_created_idx_assistance__case_id_fef8eb_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assistancecase",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="Membro da ORBE vinculado ao caso (opcional - para casos de pessoas não membros)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_assistance_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membro Vinculado",
            ),
        ),
    ]
