# Generated by Django 4.2.7 on 2025-10-03 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assistance", "0007_assistancecase_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assistancecase",
            name="member",
        ),
        migrations.AddField(
            model_name="assistancecase",
            name="linked_members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Membros da ORBE vinculados ao caso (ex: quem intermediou, fez contato, etc.)",
                related_name="linked_assistance_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membros Vinculados",
            ),
        ),
    ]
