# Generated by Django 4.2.7 on 2025-09-30 14:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competency_month",
                    models.DateField(
                        help_text="Month/Year this fee is for (e.g., 2025-01-01)",
                        verbose_name="Competency Month",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=60.0,
                        help_text="Monthly fee amount (default: R$60.00)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Calculated from user.profile.membership_due_day",
                        verbose_name="Due Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when D-0 reminder was sent",
                        null=True,
                        verbose_name="Reminder Sent At",
                    ),
                ),
                (
                    "overdue_reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when D+3 overdue reminder was sent",
                        null=True,
                        verbose_name="Overdue Reminder Sent At",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this fee",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_fees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership Fee",
                "verbose_name_plural": "Membership Fees",
                "ordering": ["-competency_month", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="finance_mem_user_id_6f23ee_idx"
                    ),
                    models.Index(
                        fields=["due_date", "status"],
                        name="finance_mem_due_dat_600fea_idx",
                    ),
                    models.Index(
                        fields=["competency_month"],
                        name="finance_mem_compete_600a04_idx",
                    ),
                ],
                "unique_together": {("user", "competency_month")},
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Donation amount (optional, can be null)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from donor",
                        verbose_name="Message",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Hide donor name in public feed",
                        verbose_name="Anonymous Donation",
                    ),
                ),
                (
                    "donated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Donated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Anonymous donations allowed (null)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation",
                "verbose_name_plural": "Donations",
                "ordering": ["-donated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "donated_at"],
                        name="finance_don_user_id_d2abe5_idx",
                    ),
                    models.Index(
                        fields=["donated_at"], name="finance_don_donated_2c69d4_idx"
                    ),
                ],
            },
        ),
    ]
