# Generated by Django 4.2.7 on 2025-10-02 14:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        help_text="Nome da pessoa/família que receberá a doação (pode ser anônimo na publicação)",
                        max_length=200,
                        verbose_name="Nome do Beneficiário",
                    ),
                ),
                (
                    "recipient_description",
                    models.TextField(
                        help_text="Informações sobre o beneficiário e sua situação",
                        verbose_name="Descrição do Beneficiário",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor aproximado necessário (R$)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Valor Estimado",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Por que essa doação é necessária (ex: cesta básica, remédios, conta de luz)",
                        verbose_name="Motivo da Necessidade",
                    ),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Nível de Urgência",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pendente de Aprovação"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        db_index=True,
                        default="pending_approval",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Explicação do admin sobre a rejeição",
                        verbose_name="Motivo da Rejeição",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aprovado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Membro que solicitou a doação",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado por",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin que aprovou/rejeitou",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_donation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Doação",
                "verbose_name_plural": "Solicitações de Doação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoluntaryDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor doado (R$)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem opcional do doador",
                        verbose_name="Mensagem",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, o nome do doador não aparecerá no feed",
                        verbose_name="Doação Anônima",
                    ),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True,
                        help_text="Comprovante de PIX/transferência (opcional)",
                        null=True,
                        upload_to="voluntary_donations/%Y/%m/",
                        verbose_name="Comprovante de Pagamento",
                    ),
                ),
                (
                    "donated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Doação"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verificado em"
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Membro que fez a doação (nulo se anônimo)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voluntary_donations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doador",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin que confirmou o recebimento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_voluntary_donations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doação Espontânea",
                "verbose_name_plural": "Doações Espontâneas",
                "ordering": ["-donated_at"],
            },
        ),
        migrations.DeleteModel(
            name="Donation",
        ),
        migrations.AddIndex(
            model_name="voluntarydonation",
            index=models.Index(
                fields=["-donated_at"], name="finance_vol_donated_854058_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voluntarydonation",
            index=models.Index(
                fields=["donor", "-donated_at"], name="finance_vol_donor_i_e6dd17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donationrequest",
            index=models.Index(
                fields=["requested_by", "status"], name="finance_don_request_7d82fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donationrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="finance_don_status_c77810_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donationrequest",
            index=models.Index(
                fields=["urgency_level", "status"],
                name="finance_don_urgency_1a670e_idx",
            ),
        ),
    ]
