# Generated by Django 4.2.7 on 2025-09-30 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for the invited member",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Unique token for password setup",
                        max_length=64,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Last Name"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("board", "Diretoria"),
                            ("fiscal_council", "Conselho Fiscal"),
                            ("member", "Membro"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Token expiration date (7 days from creation)",
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the invitation has been used",
                        verbose_name="Is Used",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin/Board member who created this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation Token",
                "verbose_name_plural": "Invitation Tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "is_used"], name="users_invit_email_d73124_idx"
                    ),
                    models.Index(
                        fields=["token", "is_used"], name="users_invit_token_74e362_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="users_invit_expires_cae9e5_idx"
                    ),
                ],
            },
        ),
    ]
