# Generated by Django 4.2.7 on 2025-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_invitationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manual (Staff/Admin)"),
                    ("invited", "Invited (Email Token)"),
                ],
                default="manual",
                help_text="How this user was registered",
                max_length=10,
                verbose_name="registration method",
            ),
        ),
        migrations.AlterField(
            model_name="invitationtoken",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("BOARD", "Diretoria"),
                    ("FISCAL_COUNCIL", "Conselho Fiscal"),
                    ("MEMBER", "Membro"),
                ],
                default="MEMBER",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("BOARD", "Diretoria"),
                    ("FISCAL_COUNCIL", "Conselho Fiscal"),
                    ("MEMBER", "Membro"),
                ],
                default="MEMBER",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
